"""Repository scaffolding: `disensor init`.

The package installs once (pipx install disensor); each repository is
initialized once with this command. Idempotent by design: running it again
respects what already exists and reports what it did, so nothing is ever
silently overwritten.

It writes three pieces, each optional by flag:
  1. disensor.config.json: the criticality level, versioned with the code.
  2. A CLAUDE.md section: the event-close instructions for Claude Code.
  3. .github/workflows/disensor.yml: the CI gate, pinned to this version.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

from . import __version__

CLAUDE_HEADING = "## disensor: residue declaration at event close"

CLAUDE_SECTION = f"""{CLAUDE_HEADING}

At the end of each adversarial review round (plan or diff), BEFORE closing
the event:

1. Run `disensor new --gate <plan|diff> --level <A|B|C>` and fill in the
   template it creates under `.residue/` with what happened in the round:
   - One finding per point raised by the reviewer (an assistant of another
     model family), with its terminal state: incorporated (with
     `remedy_adjustment` if you fixed the proposed remedy), debt_recorded
     (with id), owner_decision (with the risk record), refuted_verifiable
     (with evidence), refuted_interpretive, or escalated_open.
   - The verification of each finding (`against`: repository or execution).
   - In the diff gate, the fix verification of each incorporated finding
     (diff_gate or specific_test). Never "pending".
   - The residue: escalations without a decision, refutations of the
     principal, and execution gaps. If nothing remained, the express
     declaration of absence (concrete text, not "no residue").
   - The sha256 hash of the adversarial brief used, in `prompt_hash`.
   - `confinement.verified: true` ONLY if you ran `git status` after the
     round and it was clean.
2. Run `disensor validate` on the file. If it fails, fix it: the CI gate
   rejects exactly the same.
3. The artifact goes in its own commit (`docs(residue): declare event
   <short-id>`). Never mixed with code.
4. Do not invent findings or states: the artifact declares what happened,
   not what should have happened. An event without findings and with an
   express declaration of absence is valid pilot data, not a failure.
"""

GLOBAL_GUARD = (
    "The following applies ONLY inside repositories whose root contains "
    "`disensor.config.json`:\n\n"
)

WORKFLOW = f"""# Generated by disensor init. The gate validates the .residue/ artifacts of each PR.
name: disensor
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # the gate needs the PR commit range (check G5)
      - uses: NicolasRocchia/disensor@v{__version__}
"""

V01_CONFIG_KEYS = {"nivel_criticidad", "nivel_A_habilitado"}


def _is_git_repo(cwd: Path) -> bool:
    r = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        capture_output=True, text=True, cwd=cwd, check=False,
    )
    return r.returncode == 0 and r.stdout.strip() == "true"


def _write_config(root: Path, level: str, report: list[str]) -> None:
    path = root / "disensor.config.json"
    if path.exists():
        try:
            existing = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            existing = {}
        if V01_CONFIG_KEYS & set(existing):
            report.append(
                f"WARNING {path.name}: kept, but it uses v0.1 Spanish keys; the gate will "
                "refuse them. Rename: nivel_criticidad -> criticality_level, "
                "nivel_A_habilitado -> level_A_enabled."
            )
        else:
            report.append(f"kept    {path.name} (already exists)")
        return
    config = {"criticality_level": level, "level_A_enabled": False}
    path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    report.append(f"created {path.name} (criticality_level={level})")


def _write_claude(path: Path, section: str, label: str, report: list[str]) -> None:
    if path.exists():
        content = path.read_text(encoding="utf-8")
        if CLAUDE_HEADING in content:
            report.append(f"kept    {label} (disensor section already present)")
            return
        joiner = "" if content.endswith("\n\n") else ("\n" if content.endswith("\n") else "\n\n")
        path.write_text(content + joiner + section, encoding="utf-8")
        report.append(f"updated {label} (disensor section appended)")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(section, encoding="utf-8")
    report.append(f"created {label}")


def _write_workflow(root: Path, report: list[str]) -> None:
    path = root / ".github" / "workflows" / "disensor.yml"
    if path.exists():
        report.append(f"kept    {path.relative_to(root)} (already exists)")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(WORKFLOW, encoding="utf-8")
    report.append(f"created {path.relative_to(root)} (pinned to v{__version__})")


def main_init(args) -> int:
    root = Path.cwd()
    report: list[str] = []

    if not _is_git_repo(root):
        report.append("WARNING: this directory is not a git repository; scaffolding anyway")

    _write_config(root, args.level, report)

    if args.claude_global:
        _write_claude(
            Path.home() / ".claude" / "CLAUDE.md",
            GLOBAL_GUARD + CLAUDE_SECTION,
            "~/.claude/CLAUDE.md (global)",
            report,
        )
    elif not args.no_claude:
        _write_claude(root / "CLAUDE.md", CLAUDE_SECTION, "CLAUDE.md", report)
    else:
        report.append("skipped CLAUDE.md (--no-claude)")

    if args.no_workflow:
        report.append("skipped .github/workflows/disensor.yml (--no-workflow)")
    else:
        _write_workflow(root, report)

    for line in report:
        print(line)
    print(
        "\nNext: the adversarial loop needs a reviewer from another model family "
        "(rule R4). Close each review round with `disensor new`, fill in the "
        "artifact, and `disensor validate` it before committing."
    )
    return 0
