"""Repository scaffolding: `disensor init`.

The package installs once (pipx install disensor); each repository is
initialized once with this command. Idempotent by design: running it again
respects what already exists and reports what it did, so nothing is ever
silently overwritten.

It writes four pieces, each optional by flag:
  1. disensor.config.json: the criticality level, versioned with the code.
  2. A CLAUDE.md section: the event-close trigger for Claude Code.
  3. A Claude Code skill with the full filling guide, loaded on demand
     (the same text `disensor guide` prints for any other agent).
  4. .github/workflows/disensor.yml: the CI gate, at this version's tag.
     A tag can be moved, so the workflow says out loud that whoever deploys
     has to replace it with the commit SHA it points at.

After `pip install disensor` and `disensor init`, the user should not have
to touch anything by hand: Claude knows when (CLAUDE.md) and how (skill),
and CI enforces the result.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

from . import __version__
from .guide import guide_text

CLAUDE_HEADING = "## disensor: residue declaration at event close"

CLAUDE_SECTION = f"""{CLAUDE_HEADING}

Before closing a plan or a diff, run the round and then declare it:

1. `disensor prompt --gate <plan|diff>` prints the adversarial brief. Hand it,
   with the plan or the diff, to a reviewer from ANOTHER model family (Codex,
   Gemini, whatever is at hand: a free tier is enough). Same family as the
   generator does not count, and rule R4 rejects the declaration if you try.
2. Verify every finding against the actual code before accepting it. The
   reviewer is decorrelated, not right.
3. `disensor new --gate <plan|diff> --level <A|B|C>` creates the template
   under `.residue/`. Its `prompt_hash` is
   `disensor prompt --gate <plan|diff> --hash`.
4. Fill it following the disensor skill (`.claude/skills/disensor/SKILL.md`;
   the same guide is available as `disensor guide`). Do not invent findings
   or states: the artifact declares what happened, not what should have
   happened.
5. Run `disensor validate` on the file until it prints VALID; the CI gate
   rejects exactly the same.
6. The artifact goes in its own commit (`docs(residue): declare event
   <short-id>`), never mixed with code.
"""

GLOBAL_GUARD = (
    "The following applies ONLY inside repositories whose root contains "
    "`disensor.config.json`:\n\n"
)

SKILL_FRONTMATTER = """---
name: disensor
description: Fill and validate a disensor residue declaration (.residue/*.json) at the close of an adversarial review round. Use when closing a review event, filling the template created by `disensor new`, or fixing errors reported by `disensor validate`.
---

"""

WORKFLOW = f"""# Generated by disensor init. The gate validates the declarations each PR adds.
#
# Before this workflow means anything, see "Deployment requirements" in the
# disensor README: a strict required check, CODEOWNERS over this file and over
# the configuration, and a ruleset defined outside this repository. And replace
# the tag below with the commit SHA it points at: a tag can be moved, so it is
# not a root of trust for the code that decides whether a merge is allowed.
name: disensor
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # the gate fails closed without the PR commit range
      - uses: NicolasRocchia/disensor@v{__version__}
"""

V01_CONFIG_KEYS = {"nivel_criticidad", "nivel_A_habilitado"}


def _is_git_repo(cwd: Path) -> bool:
    r = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        capture_output=True, text=True, cwd=cwd, check=False,
    )
    return r.returncode == 0 and r.stdout.strip() == "true"


def _write_config(root: Path, level: str, report: list[str]) -> None:
    path = root / "disensor.config.json"
    if path.exists():
        try:
            existing = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            existing = {}
        if V01_CONFIG_KEYS & set(existing):
            report.append(
                f"WARNING {path.name}: kept, but it uses v0.1 Spanish keys; the gate will "
                "refuse them. Rename: nivel_criticidad -> criticality_level, "
                "nivel_A_habilitado -> level_A_enabled."
            )
        else:
            report.append(f"kept    {path.name} (already exists)")
        return
    config = {"criticality_level": level, "level_A_enabled": False}
    path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    report.append(f"created {path.name} (criticality_level={level})")


def _write_claude(path: Path, section: str, label: str, report: list[str]) -> None:
    if path.exists():
        content = path.read_text(encoding="utf-8")
        if CLAUDE_HEADING in content:
            report.append(f"kept    {label} (disensor section already present)")
            return
        joiner = "" if content.endswith("\n\n") else ("\n" if content.endswith("\n") else "\n\n")
        path.write_text(content + joiner + section, encoding="utf-8")
        report.append(f"updated {label} (disensor section appended)")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(section, encoding="utf-8")
    report.append(f"created {label}")


def _write_skill(base: Path, label: str, report: list[str]) -> None:
    path = base / ".claude" / "skills" / "disensor" / "SKILL.md"
    if path.exists():
        report.append(f"kept    {label} (already exists)")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(SKILL_FRONTMATTER + guide_text(), encoding="utf-8")
    report.append(f"created {label}")


def _write_workflow(root: Path, report: list[str]) -> None:
    path = root / ".github" / "workflows" / "disensor.yml"
    if path.exists():
        report.append(f"kept    {path.relative_to(root)} (already exists)")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(WORKFLOW, encoding="utf-8")
    report.append(
        f"created {path.relative_to(root)} (tag v{__version__}; replace it with its commit "
        "SHA, a tag is movable and is not a root of trust)"
    )


def main_init(args) -> int:
    root = Path.cwd()
    report: list[str] = []

    if not _is_git_repo(root):
        report.append("WARNING: this directory is not a git repository; scaffolding anyway")

    _write_config(root, args.level, report)

    if args.claude_global:
        home = Path.home()
        _write_claude(
            home / ".claude" / "CLAUDE.md",
            GLOBAL_GUARD + CLAUDE_SECTION,
            "~/.claude/CLAUDE.md (global)",
            report,
        )
        if not args.no_skill:
            _write_skill(home, "~/.claude/skills/disensor/SKILL.md (global)", report)
    elif not args.no_claude:
        _write_claude(root / "CLAUDE.md", CLAUDE_SECTION, "CLAUDE.md", report)
        if not args.no_skill:
            _write_skill(root, ".claude/skills/disensor/SKILL.md", report)
    else:
        report.append("skipped CLAUDE.md and skill (--no-claude)")

    if args.no_workflow:
        report.append("skipped .github/workflows/disensor.yml (--no-workflow)")
    else:
        _write_workflow(root, report)

    for line in report:
        print(line)
    print(
        "\nNext: `disensor prompt --gate <plan|diff>` prints the brief to hand to a "
        "reviewer from ANOTHER model family (rule R4; a free tier is enough). Then "
        "`disensor new` creates the declaration, the skill or `disensor guide` explains "
        "every field, and `disensor validate` checks it before committing."
    )
    return 0
